//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ирида
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodations
    {
        public int IdAccommodations { get; set; }
        public System.DateTime DateInA { get; set; }
        public System.DateTime DateOutA { get; set; }
        public int PriceA { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
