//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ирида
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel1Container : DbContext
    {
        public DBModel1Container()
            : base("name=DBModel1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Reservations> ReservationsSet { get; set; }
        public virtual DbSet<Clients> ClientsSet { get; set; }
        public virtual DbSet<Rooms> RoomsSet { get; set; }
        public virtual DbSet<Accommodations> AccommodationsSet { get; set; }
    }
}
