//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ирида
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int IdReservatons { get; set; }
        public int PriceR { get; set; }
        public System.DateTime DateReservation { get; set; }
        public System.DateTime DateInR { get; set; }
        public System.DateTime DateOutR { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
